name: MLOPS-TASK-2

on: [push]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Configure CMake
        run: cmake .

      - name: Build
        run: cmake --build .

      - name: Install dependencies
        run: cmake --build . --target install

      - name: Run tests
        run: cmake --build . --target test
